version: 2

models:
  - name: gold
    columns:
      - name: customer_id
        description: 'Customer_id is the unique and not null column'
        tests:
          - not_null
          - relationships:
              field: customer_id
              to: ref('silver')
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_name
        tests:
          - not_null
      - name: final_amount
        tests:
          - not_null
        